### PR TITLE
Multi-Part and Meta-Data

### PR DESCRIPTION
**Pull request by NassiHarel**
---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)

### CODE REVIEW

**Review by yehiyam — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[lib/s3-adapter.js, line 64 at r1](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHuQGV0-Z9pq24sCHWC:-MHuQGV0-Z9pq24sCHWD:b-uzgrtj) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/b45496343464d24406e44759bdec0c6109c6dbba/lib/s3-adapter.js#L64)):*
> ```JavaScript
> 
>     async put(options) {
>         return this._put({ ...this._parsePath(options.path), Body: options.data, Metadata: options.metadata });
> ```

where is Metadata used?
___
*[lib/s3-adapter.js, line 99 at r1](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHuQaxP3uDR32uFnctF:-MHuQaxP3uDR32uFnctG:bgjdr3u) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/b45496343464d24406e44759bdec0c6109c6dbba/lib/s3-adapter.js#L99)):*
> ```JavaScript
>      * Finally, it send a complete Multipart-Upload request.
>      */
>     async multiPart(option) {
> ```

are you using this method, or object and metadata?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[lib/s3-adapter.js, line 64 at r1](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHuQGV0-Z9pq24sCHWC:-MHugrbcA8tHEsa6sCoM:b-a974bb) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/b45496343464d24406e44759bdec0c6109c6dbba/lib/s3-adapter.js#L64)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

where is Metadata used?
</blockquote></details>

This is an s3 object.
___
*[lib/s3-adapter.js, line 99 at r1](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHuQaxP3uDR32uFnctF:-MHugyFk008pi78GXIZW:b43417y) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/b45496343464d24406e44759bdec0c6109c6dbba/lib/s3-adapter.js#L99)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

are you using this method, or object and metadata?
</blockquote></details>

for "future" use...

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-:-MHz1h_M667uF_yZeEGr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/s3-validator-replacer.js, line 74 at r3](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHz8HlA56L9jjeO9n4R:-MHz8HlA56L9jjeO9n4S:b-eq75hi) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/fa10589b10366431288ab13f980d4f765343044c/lib/s3-validator-replacer.js#L74)):*
> ```JavaScript
>                 const [k, v] = cur;
>                 if (!Buffer.isBuffer(v)) {
>                     throw new Error(`invalid metadata type ${typeof v}`);
> ```

I would encode decode just the value of "header" meta data, and allow adding regular string meta data in the future.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[lib/s3-validator-replacer.js, line 74 at r3](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHz8HlA56L9jjeO9n4R:-MHzK_je9DYhIpeTt02n:bnku5tp) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/fa10589b10366431288ab13f980d4f765343044c/lib/s3-validator-replacer.js#L74)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I would encode decode just the value of "header" meta data, and allow adding regular string meta data in the future.
</blockquote></details>

The problem is that if a string was supplied, when I decode the metadata I need to know if that string was a buffer or not... 
so I applied a more generic solution....

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[lib/s3-validator-replacer.js, line 74 at r3](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10#-MHz8HlA56L9jjeO9n4R:-MHzLrXH94a-LvuLbEba:b-896fix) ([raw file](https://github.com/kube-hpc/s3-adapter.hkube/blob/fa10589b10366431288ab13f980d4f765343044c/lib/s3-validator-replacer.js#L74)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

The problem is that if a string was supplied, when I decode the metadata I need to know if that string was a buffer or not... 
so I applied a more generic solution....
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/s3-adapter.hkube/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
